spring:
   profiles:
      active:
      - dev
---
spring:
   profiles: dev
   application:
      name: spring-eureka-server1
---
spring:
   profiles: devc
   application:
      name: spring-eureka-server2
---    
spring:
   profiles: default
   application:
      name: spring-eureka-server3

    
    
    

    
    
