spring:
  profiles:
    active:
    - dev
---
spring:
   profiles: dev
server:
   port: 8001
eureka:
   client: # 客户端进行Eureka注册的配置
      service-url:
         defaultZone: http://spring-eureka-server1:7001/eureka,http://spring-eureka-server2:7002/eureka,http://spring-eureka-server3:7003/eureka
   instance:
     lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
     lease-expiration-duration-in-seconds: 5 # 如果现在超过了5秒的间隔（默认是90秒）
     instance-id: eureka-provider-client1  # 在信息列表时显示主机名称
     prefer-ip-address: true     # 访问的路径变为IP地址
management:
   endpoints:
      web:
         exposure:
            include: '*'
   endpoint:
      health:
         show-details: ALWAYS   
    
    

---
spring:
   profiles: beta
server:
   port: 8001
eureka:
   client: # 客户端进行Eureka注册的配置
      service-url:
         defaultZone: http://spring-eureka-server1:7001/eureka,http://spring-eureka-server2:7002/eureka,http://spring-eureka-server3:7003/eureka
   instance:
     lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
     lease-expiration-duration-in-seconds: 5 # 如果现在超过了5秒的间隔（默认是90秒）
     instance-id: eureka-provider-client1  # 在信息列表时显示主机名称
     prefer-ip-address: true     # 访问的路径变为IP地址
management:
   endpoints:
      web:
         exposure:
            include: '*'
   endpoint:
      health:
         show-details: ALWAYS   
    
    

